#include <Test/EntityStressTest.h>
#include <Components/Position.h>
#include <chrono>

/// <summary>
/// Tests generated by Claude, may need tweaks.
/// </summary>
namespace Engine {
    void EntityStressTest::runMillionEntityTest() {
        constexpr i32 count = 1'000'000;
        std::vector<EntityID> ids;
        ids.reserve(count);

        auto start = std::chrono::high_resolution_clock::now();

        for (i32 i = 0; i < count; ++i) {
            EntityID id = m_ecs.createEntity();
            m_ecs.addComponent(id, Position{ .transform = Vector3double{0.0, 0.0, 0.0}, .rotation = 0.0f });
            ids.push_back(id);
        }

        auto end = std::chrono::high_resolution_clock::now();
        auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();

        EngineLogInfo(std::format("Created {} entities with Position in {}ms", count, ms).c_str());
    }

    void EntityStressTest::runChurnTest() {
        constexpr i32 initialCount = 100'000;
        constexpr i32 churnCycles = 500'000; // each cycle: one destroy + one create + addComponent

        std::vector<EntityID> ids;
        ids.reserve(initialCount);

        // Seed a working population first — churn against a "live" set, not an empty one
        for (i32 i = 0; i < initialCount; ++i) {
            EntityID id = m_ecs.createEntity();
            m_ecs.addComponent(id, Position{ .transform = Vector3double{0.0, 0.0, 0.0}, .rotation = 0.0f });
            ids.push_back(id);
        }

        auto start = std::chrono::high_resolution_clock::now();

        // Mixed create/add/remove/destroy churn against a live population,
        // mimicking mid-combat component churn rather than one-shot bulk creation
        for (i32 i = 0; i < churnCycles; ++i) {
            // pick a pseudo-random existing entity to destroy — cheap, deterministic spread
            i32 victimIndex = static_cast<i32>((static_cast<i64>(i) * 7919) % ids.size());
            EntityID victim = ids[victimIndex];

            m_ecs.destroyEntity(victim);

            EntityID replacement = m_ecs.createEntity();
            m_ecs.addComponent(replacement, Position{ .transform = Vector3double{0.0, 0.0, 0.0}, .rotation = 0.0f });
            ids[victimIndex] = replacement;

            // exercise add/remove churn on a still-alive neighbor too — the actual
            // Harm System pattern (segments gaining/losing components live)
            i32 neighborIndex = static_cast<i32>((static_cast<i64>(i) * 104729) % ids.size());
            EntityID neighbor = ids[neighborIndex];
            if (m_ecs.hasComponent<Movement>(neighbor)) {
                m_ecs.removeComponent<Movement>(neighbor);
            }
            else {
                m_ecs.addComponent(neighbor, Movement{});
            }
        }

        auto end = std::chrono::high_resolution_clock::now();
        auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(end - start).count();

        EngineLogInfo(std::format(
            "Churned {} cycles (destroy+create+Position, plus Movement add/remove) over {} live entities in {}ms",
            churnCycles, initialCount, ms
        ).c_str());
    }
}