#version 440 core
layout(local_size_x = 256) in;

struct Particle {
	vec2 position;
	vec2 velocity;
	float age;
	float maxLifetime;
};

layout(std430, binding = 0) buffer ParticleBuffer { Particle particles[]; };
uniform float dt;

void main() {
	uint i = gl_GlobalInvocationID.x;
	if (i >= particles.length()) return;
	if (particles[i].age >= particles[i].maxLifetime) return;

	particles[i].position += particles[i].velocity * dt;
	particles[i].age += dt;
}